"""Reproducible synthetic catalogue for the portfolio's interactive lab.

This pedagogical quality gate is separate from the historical Python ETL:
reject invalid dates/ratings and duplicates, retain explicit missing values.
"""
import json
import random
from datetime import date
from pathlib import Path

from generate_sample_data import build_rows


def build_catalogue():
    rng = random.Random(42)
    rows = build_rows(800, 42)
    for row in rows:
        row['ratings_count'] = max(0, int(rng.lognormvariate(7.7, 1.8)))
        row['text_reviews_count'] = int(row['ratings_count'] * rng.uniform(.01, .07))
        row['average_rating'] = round(min(4.95, max(2.0, rng.gauss(3.85, .4))), 2)
    # Preserve deliberate source defects after enrichment.
    rows[5]['average_rating'] = 7.4
    rows[11]['ratings_count'] = 0
    rows[11]['text_reviews_count'] = 0
    rows[-1] = dict(rows[0])
    seen, clean = set(), []
    report = dict(input=len(rows), duplicates=0, invalidRating=0,
                  invalidDate=0, unknownLanguage=0, missingPages=0)
    for row in rows:
        if row['bookID'] in seen:
            report['duplicates'] += 1
            continue
        seen.add(row['bookID'])
        if not 0 <= row['average_rating'] <= 5:
            report['invalidRating'] += 1
            continue
        try:
            year = date.fromisoformat(row['publication_date']).year
        except ValueError:
            report['invalidDate'] += 1
            continue
        if not row['language_code']:
            report['unknownLanguage'] += 1
        if not row['num_pages']:
            report['missingPages'] += 1
        clean.append(dict(
            id=row['bookID'], title=row['title'] + ' · ' + str(row['bookID']),
            rating=row['average_rating'], votes=row['ratings_count'],
            reviews=row['text_reviews_count'],
            language='eng' if row['language_code'] == 'en-US' else row['language_code'] or 'unknown',
            genre=row['genre_name'], year=year, pages=row['num_pages'] or None,
        ))
    report['output'] = len(clean)
    return dict(source='Synthetic catalogue; seed 42; generated by scripts/build_demo_data.py',
                quality=report, books=clean)


if __name__ == '__main__':
    catalogue = build_catalogue()
    output = Path(__file__).resolve().parents[1] / 'demo'
    output.mkdir(exist_ok=True)
    (output / 'catalogue.json').write_text(
        json.dumps(catalogue, ensure_ascii=False, separators=(',', ':')), encoding='utf-8')
    print(catalogue['quality'])
